---
- name: Download exporter
  ansible.builtin.get_url:
    url: "https://github.com/prometheus-community/elasticsearch_exporter/releases/download/v{{ version }}/elasticsearch_exporter-{{ version }}.linux-amd64.tar.gz"
    dest: /tmp/elasticsearch_exporter-{{ version }}.tar.gz
    mode: '0640'

- name: Unarchive exporter
  ansible.builtin.unarchive:
    src: /tmp/elasticsearch_exporter-{{ version }}.tar.gz
    dest: /tmp
    remote_src: true

- name: Copy elasticsearch_exporter to /usr/bin
  ansible.builtin.copy:
    src: "/tmp/elasticsearch_exporter-{{ version }}.linux-amd64/elasticsearch_exporter"
    dest: /usr/bin/elasticsearch_exporter
    mode: '0755'
    remote_src: true
  notify: Restart elasticsearch_exporter

- name: Setup service daemon
  ansible.builtin.template:
    src: elasticsearch_exporter.service.j2
    dest: /usr/lib/systemd/system/elasticsearch_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart elasticsearch_exporter

- name: Enable elasticsearch_exporter
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: elasticsearch_exporter
